### ISSUE TITLE
Feature request: Allow to specify onRun timeouts in the GUI

### ISSUE THREAD

**Issue by patrickjahns** [aws-deadline/deadline-cloud-for-cinema-4d#174]
### Describe the problem

With https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/pull/173 default timeouts for starting/stopping cinema4d have been added.
While exploring deadline-cloud in the past weeks, we noticed that on some projects cinema4d would render a scene and show a progress of 100%, but fail "to finish" the rendering in that specific project. For some reason it just "gets-stuck" - manually cancelling that task and requeuing it has solved the problem. This sometimes occured during overnight jobs and workers were "stuck" for hours at a time - which is wasted rendering time

### Proposed Solution

Adding a timeout to the `onRun` step helps to automatically re-start the individual task after a certain period of time.
As we sometimes have frames that render for several minutes - it would be great to specify the timeout for that render task in the cinema4d-submitter gui

```
  script:
    embeddedFiles:
    - name: runData
      filename: run-data.yaml
      type: TEXT
      data: |
        frame: {{Task.Param.Frame}}
    actions:
      onRun:
        command: cinema4d-openjd
        args:
        - daemon
        - run
        - --connection-file
        - '{{ Session.WorkingDirectory }}/connection.json'
        - --run-data
        - file://{{ Task.File.runData }}
        cancelation:
          mode: NOTIFY_THEN_TERMINATE
        timeout: 180 
```

Specifically add the  parameter and make it configurable in the GUI
```
        timeout: 180 
```

### Example Use Cases

As outlined before - be able to add a render timeout via the submitter GUI, so that problems with cinema4d "hanging" can be caught and the task restarted for several times
